defaults:
  - _self_
  - transfer: ${transfer}
  - eval_setup: benchmark

transfer: Food2Kitchen

src_device: "cuda"
tgt_device: "cuda"

fusion_mode: "add-before-norm"

train_src_item_emb: false
train_src_encoder: true
train_tgt_item_emb: false

epochs: 100
seed: 42
max_patience: 10
fastloader: true
batch_size: 128
checkpoint_dir: 'checkpoints'
phase: test # or train
